/* =============================================================
   Upstream — leg data
   Pure data: the ten legs of the river journey from Yangon to
   Myitsone. No DOM, no three.js — game.js interprets everything
   here. E2E lints this via window.UpstreamLegs.
   Colors are hex numbers for three.js. Distances in meters,
   speeds in m/s (world units are meters).
   ============================================================= */
(function () {
  "use strict";

  const LEGS = [
    {
      id: "yangon-pyay",
      from: { id: "yangon", en: "Yangon", mm: "ရန်ကုန်" },
      to: { id: "pyay", en: "Pyay", mm: "ပြည်" },
      distance: 1300,
      baseSpeed: 16,
      current: 3,
      riverWidth: 34,
      theme: "delta",
      newHazard: "barge",
      intro: {
        mm: "မြစ်ဝကျွန်းပေါ်က ရေကြောင်း — သင်္ဘောကြီးတွေ ရှောင်ပြီး မောင်းပါ။",
        en: "Delta traffic. Barges and ferries own this water — slip between them.",
      },
      sky: [0x8ecfe8, 0xffe9c2],
      water: [0x3e7d70, 0x2a5c55],
      fog: { color: 0xcfe8e2, near: 60, far: 210 },
      light: { sun: 0xfff2d9, sunI: 1.15, amb: 0x9fc4c9, ambI: 0.75 },
      hazards: { barge: 5, ferry: 3, log: 2, buoySafe: 2 },
      coinRate: 1.0,
    },
    {
      id: "pyay-magway",
      from: { id: "pyay", en: "Pyay", mm: "ပြည်" },
      to: { id: "magway", en: "Magway", mm: "မကွေး" },
      distance: 1400,
      baseSpeed: 16.5,
      current: 3,
      riverWidth: 34,
      theme: "dry",
      newHazard: "sandbar",
      intro: {
        mm: "နွေရာသီ ရေတိမ်ပိုင်း — သဲသောင်ခုံတွေကို သတိထားပါ။",
        en: "The dry zone. The river runs shallow — read the water, dodge the sandbars.",
      },
      sky: [0xa8d4e8, 0xffe2ad],
      water: [0x6e8a5e, 0x4f6b48],
      fog: { color: 0xe8dfc4, near: 70, far: 230 },
      light: { sun: 0xffe9bf, sunI: 1.25, amb: 0xc4bfa0, ambI: 0.7 },
      hazards: { sandbar: 5, log: 3, barge: 2, fisher: 2 },
      coinRate: 1.0,
    },
    {
      id: "magway-bagan",
      from: { id: "magway", en: "Magway", mm: "မကွေး" },
      to: { id: "bagan", en: "Bagan", mm: "ပုဂံ" },
      distance: 1500,
      baseSpeed: 17,
      current: 3.5,
      riverWidth: 34,
      theme: "bagan",
      newHazard: "whirlpool",
      intro: {
        mm: "ရေဝဲတွေ စတွေ့ပြီ — ဝဲထဲမနစ်အောင် ဘေးက ကွေ့ပါ။",
        en: "Whirlpools spin in the deep channel. Swing wide or they'll drag you.",
      },
      sky: [0xf5b880, 0xffdf9e],
      water: [0x77754a, 0x4f5638],
      fog: { color: 0xf3d6a8, near: 65, far: 220 },
      light: { sun: 0xffcf8a, sunI: 1.2, amb: 0xd9b48a, ambI: 0.72 },
      hazards: { whirlpool: 5, sandbar: 2, log: 2, fisher: 2 },
      coinRate: 1.1,
    },
    {
      id: "bagan-pakokku",
      from: { id: "bagan", en: "Bagan", mm: "ပုဂံ" },
      to: { id: "pakokku", en: "Pakokku", mm: "ပခုက္ကူ" },
      distance: 1400,
      baseSpeed: 17,
      current: 4,
      riverWidth: 34,
      theme: "thanaka",
      newHazard: "net",
      home: true,
      intro: {
        mm: "ချင်းတွင်းမြစ်ဆုံ ရေစီးကြမ်း — ပိုက်ကွန်တွေကြားက အိမ်ပြန်လမ်း။",
        en: "The Chindwin joins here — crosscurrents and fishing nets. The road home.",
      },
      sky: [0x9fd4e0, 0xfff0c8],
      water: [0x527a63, 0x3a5c4c],
      fog: { color: 0xd8ecd9, near: 65, far: 225 },
      light: { sun: 0xfff0cf, sunI: 1.18, amb: 0xa8c9ad, ambI: 0.78 },
      hazards: { net: 5, whirlpool: 2, log: 2, ferry: 2 },
      crosswind: 2.2,
      coinRate: 1.2,
      landmark: "bridge",
    },
    {
      id: "pakokku-mandalay",
      from: { id: "pakokku", en: "Pakokku", mm: "ပခုက္ကူ" },
      to: { id: "mandalay", en: "Mandalay", mm: "မန္တလေး" },
      distance: 1500,
      baseSpeed: 17.5,
      current: 3.5,
      riverWidth: 34,
      theme: "night",
      night: true,
      newHazard: "lantern",
      intro: {
        mm: "ညအမှောင်ထဲ မီးအိမ်တွေက လမ်းပြမယ် — မီးနီကို ရှောင်ပါ။",
        en: "A night run. Gold lanterns mark safe water — steer clear of the red ones.",
      },
      sky: [0x1a2745, 0x35486e],
      water: [0x24406e, 0x16294a],
      fog: { color: 0x22304f, near: 45, far: 165 },
      light: { sun: 0xa8bce8, sunI: 0.7, amb: 0x56689a, ambI: 1.2 },
      hazards: { lantern: 5, log: 3, barge: 2, whirlpool: 1 },
      coinRate: 1.1,
      landmark: "avabridge",
    },
    {
      id: "mandalay-kyaukmyaung",
      from: { id: "mandalay", en: "Mandalay", mm: "မန္တလေး" },
      to: { id: "kyaukmyaung", en: "Kyaukmyaung", mm: "ကျောက်မြောင်း" },
      distance: 1500,
      baseSpeed: 17.5,
      current: 4,
      riverWidth: 34,
      theme: "storm",
      storm: true,
      newHazard: "debris",
      intro: {
        mm: "မိုးသက်မုန်တိုင်း — မိုးထဲက မျောလာတဲ့ အပျက်အစီးတွေ သတိ။",
        en: "Monsoon squall. Rain hammers the river and the storm sends debris downstream.",
      },
      sky: [0x3f4a58, 0x6b7684],
      water: [0x35494f, 0x223338],
      fog: { color: 0x4d5a66, near: 50, far: 170 },
      light: { sun: 0x9fb0bf, sunI: 0.6, amb: 0x5e6d7a, ambI: 0.9 },
      hazards: { debris: 5, log: 3, whirlpool: 2, sandbar: 1 },
      coinRate: 1.15,
    },
    {
      id: "kyaukmyaung-katha",
      from: { id: "kyaukmyaung", en: "Kyaukmyaung", mm: "ကျောက်မြောင်း" },
      to: { id: "katha", en: "Katha", mm: "ကသာ" },
      distance: 1600,
      baseSpeed: 18,
      current: 4,
      riverWidth: 34,
      theme: "teak",
      newHazard: "raft",
      intro: {
        mm: "ကျွန်းသစ်ဖောင်တွေ မျောလာပြီ — ဖောင်ကြီးတွေက နေရာယူတယ်။",
        en: "Teak country. Log rafts ride the current — wide, slow, and unforgiving.",
      },
      sky: [0x9cc9b8, 0xf2e6b8],
      water: [0x3f6b52, 0x2b4d3b],
      fog: { color: 0xc2dcc6, near: 60, far: 210 },
      light: { sun: 0xf7ecc4, sunI: 1.05, amb: 0x8fb59a, ambI: 0.8 },
      hazards: { raft: 5, log: 4, debris: 1, fisher: 2 },
      coinRate: 1.2,
    },
    {
      id: "katha-bhamo",
      from: { id: "katha", en: "Katha", mm: "ကသာ" },
      to: { id: "bhamo", en: "Bhamo", mm: "ဗန်းမော်" },
      distance: 1600,
      baseSpeed: 18,
      current: 4.5,
      riverWidth: 24,
      theme: "defile",
      newHazard: "rock",
      intro: {
        mm: "မြစ်ကျဉ်း — ကျောက်ဆောင်နံရံကြားမှာ မြစ်က ကျဉ်းသွားပြီ။",
        en: "The defile. Cliff walls squeeze the river to a corridor of rock.",
      },
      sky: [0x88b8c9, 0xd9e8d4],
      water: [0x2e5e5e, 0x1d4343],
      fog: { color: 0xa8c9c2, near: 45, far: 170 },
      light: { sun: 0xe8f0d9, sunI: 0.95, amb: 0x7a9e9a, ambI: 0.85 },
      hazards: { rock: 5, log: 3, whirlpool: 2 },
      coinRate: 1.3,
    },
    {
      id: "bhamo-myitkyina",
      from: { id: "bhamo", en: "Bhamo", mm: "ဗန်းမော်" },
      to: { id: "myitkyina", en: "Myitkyina", mm: "မြစ်ကြီးနား" },
      distance: 1700,
      baseSpeed: 18.5,
      current: 5,
      riverWidth: 28,
      theme: "north",
      newHazard: "shoal",
      intro: {
        mm: "မြောက်ပိုင်းရေစီး — ကျောက်တန်းတွေ ထိုးထွက်နေတဲ့ မြစ်ကြမ်း။",
        en: "Kachin water. The current races and rock shoals tear the surface white.",
      },
      sky: [0xa2c4de, 0xe8f0e0],
      water: [0x2a5560, 0x1a3d47],
      fog: { color: 0xbdd6dc, near: 55, far: 190 },
      light: { sun: 0xf0f4e0, sunI: 1.0, amb: 0x89a8b5, ambI: 0.82 },
      hazards: { shoal: 5, rock: 3, log: 2, raft: 1 },
      coinRate: 1.3,
    },
    {
      id: "myitkyina-myitsone",
      from: { id: "myitkyina", en: "Myitkyina", mm: "မြစ်ကြီးနား" },
      to: { id: "myitsone", en: "Myitsone", mm: "မြစ်ဆုံ" },
      distance: 1800,
      baseSpeed: 19,
      current: 5.5,
      riverWidth: 26,
      theme: "myitsone",
      finale: true,
      newHazard: "rapids",
      intro: {
        mm: "နောက်ဆုံးခရီး — မေခ၊ မလိခ ဆုံရာအထိ ရေကြမ်းကို ဆန်တက်ပါ။",
        en: "The last leg. Run the rapids up to where the N'Mai Kha and Mali Kha marry.",
      },
      sky: [0x8fc4d9, 0xfdf3d0],
      water: [0x2e6b5e, 0x1e4d43],
      fog: { color: 0xcfe8dc, near: 55, far: 200 },
      light: { sun: 0xfff4d4, sunI: 1.1, amb: 0x94bfae, ambI: 0.8 },
      hazards: { rapids: 4, rock: 4, shoal: 2, log: 1 },
      coinRate: 1.4,
      confluence: true,
    },
  ];

  /* Boat upgrades sold in town shops.
     availableFrom = leg index of the first town that stocks it
     (towns are visited after finishing leg i, so 0 = Pyay). */
  const UPGRADES = {
    hull: {
      en: "Hull planks", mm: "လှေကိုယ်ထည်",
      desc: { en: "One more heart of hull strength.", mm: "အသည်းတစ်လုံး ပိုခံနိုင်မယ်။" },
      icon: "🛡️", levels: [80, 220], availableFrom: 0,
    },
    engine: {
      en: "Longtail engine", mm: "စက်ခေါင်း",
      desc: { en: "Faster upstream, sharper steering.", mm: "ပိုမြန်မြန်ဆန်တက်၊ ပိုသွက်သွက် ကွေ့။" },
      icon: "⚙️", levels: [70, 160, 300], availableFrom: 0,
    },
    charm: {
      en: "Hintha charm", mm: "ဟင်္သာအဆောင်",
      desc: { en: "Coins drift toward the boat.", mm: "အသပြာတွေ လှေဆီ မျောလာမယ်။" },
      icon: "🪙", levels: [90, 200], availableFrom: 1,
    },
    lantern: {
      en: "Boat lantern", mm: "လှေမီးအိမ်",
      desc: { en: "See farther through night and fog.", mm: "ညနဲ့ မြူထဲမှာ ပိုဝေးဝေး မြင်ရမယ်။" },
      icon: "🏮", levels: [110], availableFrom: 3,
    },
  };

  window.UpstreamLegs = {
    version: 1,
    legs: LEGS,
    upgrades: UPGRADES,
    baseHearts: 3,
    coinValue: 1,
    padaukValue: 5,
  };
})();
